services:
  - type: web
    name: get-li3b-slots
    env: node
    buildCommand: "npm install"
    startCommand: "node fetch_pageAPI.js"
    autoDeploy: true
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
    addons:
      - plan: chrome
        name: chrome
